// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbf0GSv5sTFzxGD4dwch4by-Q0dkZs-2o',
    appId: '1:883263555862:web:d2864c53c5f8fd15346837',
    messagingSenderId: '883263555862',
    projectId: 'regen-gamified',
    authDomain: 'regen-gamified.firebaseapp.com',
    storageBucket: 'regen-gamified.firebasestorage.app',
    measurementId: 'G-NWG83C25V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSCF9ihTBgzC67AmrGyBh7XJkYwOXR9Lw',
    appId: '1:883263555862:android:fcebde672434b7b0346837',
    messagingSenderId: '883263555862',
    projectId: 'regen-gamified',
    storageBucket: 'regen-gamified.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdvKlrRW801OyJgJKSoWG3wn_tzhvlhEM',
    appId: '1:883263555862:ios:12de992b0e1acd0d346837',
    messagingSenderId: '883263555862',
    projectId: 'regen-gamified',
    storageBucket: 'regen-gamified.firebasestorage.app',
    iosBundleId: 'com.example.testingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdvKlrRW801OyJgJKSoWG3wn_tzhvlhEM',
    appId: '1:883263555862:ios:12de992b0e1acd0d346837',
    messagingSenderId: '883263555862',
    projectId: 'regen-gamified',
    storageBucket: 'regen-gamified.firebasestorage.app',
    iosBundleId: 'com.example.testingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbf0GSv5sTFzxGD4dwch4by-Q0dkZs-2o',
    appId: '1:883263555862:web:a562cb9750386d1b346837',
    messagingSenderId: '883263555862',
    projectId: 'regen-gamified',
    authDomain: 'regen-gamified.firebaseapp.com',
    storageBucket: 'regen-gamified.firebasestorage.app',
    measurementId: 'G-E7KR1YDQDQ',
  );
}
